# Generated by Django 3.2.9 on 2021-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211119_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие sd карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем встроеной памяти'),
        ),
    ]
