# Generated by Django 3.2.9 on 2021-12-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211203_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='adress',
        ),
    ]
